name: "New Post (Form)"
description: "Form to create a new post with frontmatter and an iframe"
title: "Create a new post"
labels: ["new-post"]
body:
  - type: input
    id: post_title
    attributes:
      label: "Title"
      description: "Title of the post"
      placeholder: "E.g.: My new post"
    validations:
      required: true

  - type: input
    id: post_date
    attributes:
      label: "Date"
      description: "Date in format DD-MM-YYYY"
      placeholder: "22-12-2024"
    validations:
      required: true

  - type: dropdown
    id: post_visible
    attributes:
      label: "Visible"
      description: "Is the post visible?"
      options:
        - "true"
        - "false"
    validations:
      required: true

  - type: dropdown
    id: post_quote
    attributes:
      label: "Quote"
      description: "Is the post a quote?"
      options:
        - "true"
        - "false"
    validations:
      required: true

  - type: input
    id: post_slug
    attributes:
      label: "Slug"
      description: "Unique slug for the post"
      placeholder: "e.g.: 22122024"
    validations:
      required: true

  - type: input
    id: youtube_id
    attributes:
      label: "YouTube ID"
      description: "The part after /embed/, e.g.: iOAEEL5rX1s"
      placeholder: "iOAEEL5rX1s"
    validations:
      required: false
